#!/bin/sh

WIFI_INTERFACE="wlp0s20f3"
INTERNET_INTERFACE="lo"
SSID="GarmJagah"
DEFAULT_PASSWORD="hotshots"

PASSWORD=${1:-$DEFAULT_PASSWORD}

sudo create_ap $WIFI_INTERFACE $INTERNET_INTERFACE $SSID $PASSWORD